name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        run: |
          yarn
          yarn web-build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          keep_files: false

      - name: Publish
        uses: actions/upload-artifact@v3
        with:
          path: /out/make/zip/win32/x64/*